language: java

jdk:
  - oraclejdk8

os:
  - linux

script:
  - mvn clean install

services:
  - mysql

before_script:
  - mysql -u root -e "create database datablink_message_crypto;"
  - mysql -u root -e "create user 'dbmc_user'@'localhost' identified by 'dbmc_password';"
  - mysql -u root -e "grant all on datablink_message_crypto.* to 'dbmc_user'@'localhost';"
